name: Az login

on:
  workflow_call: 
   secrets:
      AZURE_CREDENTIALS:
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: 'Login via Azure CLI'
      uses: azure/actions/login@v1
      with:
        #store this as secrets in github
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
