name: Test & Build Using Java & Maven, publish test results
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  github-actions-build: 
    uses: github-poc-ado/Reuseable-workflow/.github/workflows/build_caller.yml@main
