name: Install Java and Build using Maven

on:
  workflow_call: 
    inputs:
       java-version:
          description: 'Java Version'
          required: true
          default: '11'
          type: string
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ github.event.inputs.java-version }}
          distribution: 'adopt'
          cache: maven
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app
