name: Node With AKS WorkFlow
on: 
  workflow_call:
    inputs:
      NODE_VERSION:
        type: string 
        description: Node JS Version
        required: true
        default: '14.16'
      NPM_COMMAND_BACKEND:
        type: string 
        description: NPM Command to execute for Backend of the app
        required: true
        default: 'npm run build'
      NPM_COMMAND_FRONTEND:
        type: string 
        description: NPM Command to execute for Frontend of the app
        required: true
        default: 'npm run build'
      APP_NAME:
        type: string 
        description: APP_NAME
        required: false
        default: ''                
      DOCKER_NONPROD_REGISTRY_NAME:
        required: false
        type: string
      DOCKER_PROD_REGISTRY_NAME:
        required: false
        type: string
      DOCKER_FILE_NAME:
        required: false
        type: string 
      DOCKER_FILE_DIR:
        required: false
        type: string            
      advanceSecurityEnabled:
        type: boolean 
        description: GitHub Advanced Security
        default: False        
    secrets:
      CODEQL_TOKEN:
        required: false 
      DOCKER_USERNAME:
        required: false
      DOCKER_PASSWORD:
        required: false
      DOCKER_NONPROD_REGISTRY_NAME:
        required: false
      DOCKER_PROD_REGISTRY_NAME:
        required: false
jobs:
  ci_phase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ inputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}
      - name: NPM Install
        run: npm install
      - name: NPM Build for Backend
        if:  ${{ inputs.NPM_COMMAND_BACKEND }}
        run: ${{ inputs.NPM_COMMAND_BACKEND }}      
      - name: NPM Build for Frontend
        if:  ${{ inputs.NPM_COMMAND_FRONTEND }}
        run: ${{ inputs.NPM_COMMAND_FRONTEND }} 
      - name: NPM Test
        run: npm test
