name: Java Maven Workflow
on: 
  workflow_call:
    inputs:
      java_version:
        type: string
        description: Java Version
        required: true
        default: '11'
      REGISTRY_NAME:
        required: false
        type: string
      perform_unit_test:
        type: boolean
        description: Junit Test
        default: true
      perform_integration_test:
        type: boolean
        description: Integration Test   
        default: False
      perform_deploy:
        type: boolean
        description: Deploy
        default: False
      perform_docker_build:
        type: boolean
        description: Deploy
        default: False
      advancedSecurityEnabled:
        type: boolean
        description: GitHub Advanced Security
        default: False
      CLUSTER_NAME:
        required: False
        type: string
      CLUSTER_RESOURCE_GROUP:
        required: False
        type: string
      NAMESPACE:
        required: False
        type: string
    secrets:
      token:
        required: false
      username:
        required: false
      password:
        required: false
      creds:
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up ${{inputs.java_version}}
        uses: actions/setup-java@v3
        with:
          java-version: '${{inputs.java_version}}'
          distribution: 'temurin'
          cache: maven
      - name: Maven Build
        run: mvn --batch-mode --update-snapshots install
      - name: 'Dependency Review'
        if: ${{inputs.advancedSecurityEnabled}}
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: moderate        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'                
  test:
    runs-on: ubuntu-latest
    needs: build
    if: ${{inputs.perform_unit_test}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11 ${{inputs.java_version}}
        uses: actions/setup-java@v3
        with:
          java-version: '${{inputs.java_version}}'
          distribution: 'temurin'
      - name: Junit Test
        run: mvn --batch-mode --update-snapshots test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files:
            target/surefire-reports/*.xml
          check_name: 'Test Results'
  integration-test:
    runs-on: ubuntu-latest
    needs: build
    if: ${{inputs.perform_integration_test}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up  ${{inputs.java_version}}
        uses: actions/setup-java@v3
        with:
          java-version: '${{inputs.java_version}}'
          distribution: 'temurin'
      - name: Junit Integration Test
        run: mvn --batch-mode --update-snapshots verify
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files:
            target/surefire-reports/*.xml
          check_name: 'Integration Test Results'
  codeql-dependabot-report:
    runs-on: ubuntu-latest
    needs: build
    if: ${{inputs.advancedSecurityEnabled}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      - name: Generate Security Report
        #uses: peter-murray/github-security-report-action@v2
        uses: rsdmike/github-security-report-action@v3.0.4
        with:
          token: ${{ secrets.token }}  
          sarifReportDir: "../results"
          outputDir: ${{ github.workspace }}
          repository: ${{ github.repository }}
      - name: Upload Security Report
        uses: actions/upload-artifact@v2
        with:
          name: security-report
          path: '${{ github.workspace }}/*.pdf' 
          
  docker-image-build-push:
    env:
      REGISTRY_NAME: '${{ inputs.REGISTRY_NAME }}'
    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{inputs.perform_docker_build}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Docker Login (Connect to Azure Container registry (ACR))
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.username }} 
        #username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.password }}
       #password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Container build and push to a Azure Container registry (ACR)
      run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/myimage:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/myimage:${{ github.sha }}  
        
  deploy:
    # Environment variables available to all jobs and steps in this workflow
    env:
      REGISTRY_NAME: '${{ inputs.REGISTRY_NAME }}'
      CLUSTER_NAME: '${{ inputs.CLUSTER_NAME }}'
      CLUSTER_RESOURCE_GROUP: '${{ inputs.CLUSTER_RESOURCE_GROUP }}'
      NAMESPACE: '${{ inputs.NAMESPACE }}'
    runs-on: ubuntu-latest    
    environment: dev 
    needs:
      - build
      - test 
      - docker-image-build-push
    if: ${{inputs.perform_deploy}}
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: java-app
        
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set Up AKS
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.creds }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}   
        
    - name: Create namespace if does not exist
      run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -
        
    - name: Create imagepullsecret for Azure Container registry (ACR)
      uses: azure/k8s-create-secret@v1
      with:
        container-registry-url: ${{ env.REGISTRY_NAME }}.azurecr.io
        container-registry-username: ${{ secrets.username }}
        container-registry-password: ${{ secrets.password }}
        secret-name: ${{ env.REGISTRY_NAME }}-registry-connection
        namespace: ${{ env.NAMESPACE }}
  
    - name: Deploy app to AKS
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          ${{ env.REGISTRY_NAME }}.azurecr.io/myimage:${{ github.sha }}
        imagepullsecrets: |
          ${{ env.REGISTRY_NAME }}-registry-connection
        namespace: ${{ env.NAMESPACE }}
      
